### ISSUE TITLE
Why can't it find dumps of things that do have resources?

### ISSUE THREAD

**Issue by karl-police** [axstin/qtextract#4]
So I've tested it. And it can't find resources from everything for some reason.

**Comment by axstin** [comment]
Could you send me the binary you're trying to extract from? or the name of the software? I've only tested with a few apps, namely Roblox Studio, Wireshark, and Binary Ninja.

**Comment by axstin** [comment]
Hi,

I added a [new signature](https://github.com/axstin/qtextract/commit/231594067458b6eb67c08d8be6af412653dc093a) and qtextract now works with Chatterino builds. Note that Chatterino is open source and all Qt resources can be found here: https://github.com/Chatterino/chatterino2/tree/master/resources

Also: the Roblox client and launcher do not have any Qt resources.

**Comment by karl-police** [comment]
> Hi,
> 
> I added a [new signature](https://github.com/axstin/qtextract/commit/231594067458b6eb67c08d8be6af412653dc093a) and qtextract now works with Chatterino builds. Note that Chatterino is open source and all Qt resources can be found here: https://github.com/Chatterino/chatterino2/tree/master/resources
> 
> Also: the Roblox client and launcher do not have any Qt resources.

Yeah, I know it has all resources. But I wanted to mention that qtextract couldn't extract from it, so there might be other things it can't extract from if it's fixed.

**Comment by karl-police** [comment]
@axstin how did you figure out how to develop an extractor?
