### ISSUE TITLE
thread 'main' panicked at 'failed to parse node'

### ISSUE THREAD

**Issue by karl-police** [axstin/qtextract#6]
I've tried to check this .DLL game\bin\win64\tools\cs2_item_editor.dll

![image](https://github.com/axstin/qtextract/assets/12023782/68017daa-c76e-4bd0-9089-5f70d9159258)

idk if it has valid stuff in it, though it's a Qt thing

**Comment by axstin** [comment]
Looks like this is a false positive. I've updated qtextract not to panic in the case of parse failure.

**To future readers**: This DLL is from Valve's [Counter Strike 2 Workshop Tools](https://developer.valvesoftware.com/wiki/Counter-Strike_2_Workshop_Tools/Installing_and_Launching_Tools). Although the binaries in `game\bin\win64\tools\` have Qt imports, I don't believe they hold any resources. Resources _can_ be found in `game\bin\win64\vconsole2.exe` and `game\bin\win64\csgocfg.exe`.

**Comment by karl-police** [comment]
> Looks like this is a false positive. I've updated qtextract not to panic in the case of parse failure.
> 
> **To future readers**: This DLL is from Valve's [Counter Strike 2 Workshop Tools](https://developer.valvesoftware.com/wiki/Counter-Strike_2_Workshop_Tools/Installing_and_Launching_Tools). Although the binaries in `game\bin\win64\tools\` have Qt imports, I don't believe they hold any resources. Resources _can_ be found in `game\bin\win64\vconsole2.exe` and `game\bin\win64\csgocfg.exe`.

could be

the old cs:go v8.dll doesn't give that false positive though comparison to cs2's v8.dll
